# -*- coding: utf-8 -*-
"""
天翼云等保专区报价生成器数据模块
数据来源: 天翼云等保专区安全产品报价表.md
更新日期: 2026-04-27
"""
import copy
from typing import List, Dict

# 安全产品列表
PRODUCTS: List[Dict] = [
{
        "id": 1,
        "category": "云安全中心",
        "name": "云安全中心-标准版",
        "spec": "包含日志分析量为每月50G；云安全中心系统主要包含安全态势、资产中心、风险管理、威胁管理、分析中心、告警管理、编排响应、报表中心、集成配置以及数据源监控等功能。",
        "monthly_price": 1600,
        "yearly_price": 19200,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，享受1年及以上8.5折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 2,
        "category": "云安全中心",
        "name": "云安全中心-态势大屏",
        "spec": "包括安全成果态势、威胁攻击态势大屏",
        "monthly_price": 4500,
        "yearly_price": 54000,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，享受1年及以上8.5折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 3,
        "category": "云安全中心",
        "name": "云安全中心-日志分析量",
        "spec": "默认需购买500G日志分析量，额外购买步长为50G",
        "monthly_price": 225,
        "yearly_price": 2700,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，享受1年及以上8.5折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 4,
        "category": "主机安全",
        "name": "主机安全-旗舰版",
        "spec": "按照需防护的主机个数购买，提供安全概览、资产管理、入侵检测、漏洞扫描、基线管理功能。",
        "monthly_price": 180,
        "yearly_price": 2160,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年7折，3、4、5年5折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 5,
        "category": "主机安全",
        "name": "主机安全-网页防篡改版",
        "spec": "按照需防护的主机个数购买，提供网页防篡改能力，解决页面篡改、挂马、暗链等网页风险问题。",
        "monthly_price": 980,
        "yearly_price": 11760,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年7折，3、4、5年5折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 6,
        "category": "Web应用防火墙",
        "name": "Web应用防火墙-SaaS版-标准版",
        "spec": "业务请求峰值3000QPS，支持防护域名20个（包含2个主域名），防护端口20个，更多信息请参见产品规格。精准覆盖各类Web应用攻击，为客户识别恶意请求，防御未知威胁，分钟级接入实现防入侵、防扫描、防攻击、防数据泄露、防CC攻击等防护，等保必备。",
        "monthly_price": 3880,
        "yearly_price": 46560,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "• 包年订购折扣 针对一次性包年付费服务，包年优惠价格为1年85折，2年7折，3、4、5年5折。• 优惠折扣 Web应用防火墙v2.0 SaaS版订购享受8折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 7,
        "category": "Web应用防火墙",
        "name": "Web应用防火墙-带宽扩展包",
        "spec": "单个防护带宽扩展包，每个扩展包规格50Mb，可叠加；单个Web应用防火墙最大支持1000Mb流量，最大可支持16个扩展包。",
        "monthly_price": 500,
        "yearly_price": 6000,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "-",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 8,
        "category": "Web应用防火墙",
        "name": "Web应用防火墙-SaaS版-标准版-业务扩展包",
        "spec": "一个业务扩展包包含1000QPS/个，最多支持30个业务扩展包，每增加一个业务扩展包，可增加50Mbps带宽弹性上限，100Mbps带宽保护上限。",
        "monthly_price": 1000,
        "yearly_price": 12000,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "• 包年订购折扣 针对一次性包年付费服务，包年优惠价格为1年85折，2年7折，3、4、5年5折。• 优惠折扣 Web应用防火墙v2.0 SaaS版订购享受8折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 9,
        "category": "Web应用防火墙",
        "name": "Web应用防火墙-SaaS版-标准版-规则扩展包",
        "spec": "一个规则扩展包包含50条防护规则/域名，当前仅适用IP黑白名单防护模块。",
        "monthly_price": 70,
        "yearly_price": 840,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "• 包年订购折扣 针对一次性包年付费服务，包年优惠价格为1年85折，2年7折，3、4、5年5折。• 优惠折扣 Web应用防火墙v2.0 SaaS版订购享受8折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 10,
        "category": "Web应用防火墙",
        "name": "Web应用防火墙-独享版-单机版",
        "spec": "支持0-1Gbps的业务防护，默认业务请求峰值3000QPS（200Mbps），默认防护域名（不区分主域名、子域名）/IP（公网IP、私网IP）个数100个/实例，防护端口数最大支持65535个（常用端口除外），更多信息请参见产品规格。精准覆盖各类Web应用攻击，为客户识别恶意请求，防御未知威胁，分钟级接入实现防入侵、防扫描、防攻击、防数据泄露、防CC攻击等防护，等保必备。",
        "monthly_price": 2837,
        "yearly_price": 34044,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "-",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 11,
        "category": "Web应用防火墙",
        "name": "Web应用防火墙-独享版-域名扩展包",
        "spec": "1个域名扩展包支持10个域名或IP。",
        "monthly_price": 500,
        "yearly_price": 6000,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "-",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 12,
        "category": "Web应用防火墙",
        "name": "Web应用防火墙-独享版-带宽扩展包",
        "spec": "1个带宽扩展包包含1000QPS业务请求峰值、50Mbps业务带宽。",
        "monthly_price": 500,
        "yearly_price": 6000,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "-",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 14,
        "category": "下一代防火墙",
        "name": "下一代防火墙-标准版",
        "spec": "支持1Gbps公网流量处理能力峰值（每秒数据包处理能力：200000 PPS）；提供云上互联网边界和VPC边界的防护，包括：实时入侵检测与防御、全局统一访问控制、全流量分析可视化、日志审计与溯源分析。",
        "monthly_price": 1879,
        "yearly_price": 22548,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "-",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 15,
        "category": "下一代防火墙",
        "name": "下一代防火墙-高级版",
        "spec": "支持2Gbps公网流量处理能力峰值（每秒数据包处理能力：400000 PPS）；提供云上互联网边界和VPC边界的防护，包括：实时入侵检测与防御、全局统一访问控制、全流量分析可视化、日志审计与溯源分析。",
        "monthly_price": 3406,
        "yearly_price": 40872,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "-",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 16,
        "category": "下一代防火墙",
        "name": "下一代防火墙-企业版",
        "spec": "支持4Gbps公网流量处理能力峰值（每秒数据包处理能力：2500000 PPS）；提供云上互联网边界和VPC边界的防护，包括：实时入侵检测与防御、全局统一访问控制、全流量分析可视化、日志审计与溯源分析。",
        "monthly_price": 5673,
        "yearly_price": 68076,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "-",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 20,
        "category": "日志审计",
        "name": "日志审计-10资产",
        "spec": "支持10个日志源（每个日志源对应为一个IP）；通过主被动结合的方式，实时不间断地采集用户网络中各种不同厂商的安全设备、网络设备、主机、操作系统、以及各种应用系统产生的海量日志信息，并将这些信息汇集到审计中心，进行集中化存储（可根据日志规模大小进行分布式存储，支持水平弹性扩展和数据高可靠性存储）、索引、备份、全文检索、实时搜索、审计、告警、响应，并出具丰富的报表报告，获悉全网的整体安全运行态势，实现全生命周期的日志管理。",
        "monthly_price": 1107,
        "yearly_price": 13284,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年75折，3、4、5年65折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 21,
        "category": "日志审计",
        "name": "日志审计-15资产",
        "spec": "支持15个日志源（每个日志源对应为一个IP）；通过主被动结合的方式，实时不间断地采集用户网络中各种不同厂商的安全设备、网络设备、主机、操作系统、以及各种应用系统产生的海量日志信息，并将这些信息汇集到审计中心，进行集中化存储（可根据日志规模大小进行分布式存储，支持水平弹性扩展和数据高可靠性存储）、索引、备份、全文检索、实时搜索、审计、告警、响应，并出具丰富的报表报告，获悉全网的整体安全运行态势，实现全生命周期的日志管理。",
        "monthly_price": 1257,
        "yearly_price": 15084,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年75折，3、4、5年65折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 22,
        "category": "日志审计",
        "name": "日志审计-20资产",
        "spec": "支持20个日志源（每个日志源对应为一个IP）；通过主被动结合的方式，实时不间断地采集用户网络中各种不同厂商的安全设备、网络设备、主机、操作系统、以及各种应用系统产生的海量日志信息，并将这些信息汇集到审计中心，进行集中化存储（可根据日志规模大小进行分布式存储，支持水平弹性扩展和数据高可靠性存储）、索引、备份、全文检索、实时搜索、审计、告警、响应，并出具丰富的报表报告，获悉全网的整体安全运行态势，实现全生命周期的日志管理。",
        "monthly_price": 1582,
        "yearly_price": 18984,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年75折，3、4、5年65折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 23,
        "category": "日志审计",
        "name": "日志审计-50资产",
        "spec": "支持50个日志源（每个日志源对应为一个IP）；通过主被动结合的方式，实时不间断地采集用户网络中各种不同厂商的安全设备、网络设备、主机、操作系统、以及各种应用系统产生的海量日志信息，并将这些信息汇集到审计中心，进行集中化存储（可根据日志规模大小进行分布式存储，支持水平弹性扩展和数据高可靠性存储）、索引、备份、全文检索、实时搜索、审计、告警、响应，并出具丰富的报表报告，获悉全网的整体安全运行态势，实现全生命周期的日志管理。",
        "monthly_price": 3219,
        "yearly_price": 38628,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年75折，3、4、5年65折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 24,
        "category": "日志审计",
        "name": "日志审计-100资产",
        "spec": "支持100个日志源（每个日志源对应为一个IP）；通过主被动结合的方式，实时不间断地采集用户网络中各种不同厂商的安全设备、网络设备、主机、操作系统、以及各种应用系统产生的海量日志信息，并将这些信息汇集到审计中心，进行集中化存储（可根据日志规模大小进行分布式存储，支持水平弹性扩展和数据高可靠性存储）、索引、备份、全文检索、实时搜索、审计、告警、响应，并出具丰富的报表报告，获悉全网的整体安全运行态势，实现全生命周期的日志管理。",
        "monthly_price": 4599,
        "yearly_price": 55188,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年75折，3、4、5年65折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 25,
        "category": "日志审计",
        "name": "日志审计-200资产",
        "spec": "支持200个日志源（每个日志源对应为一个IP）；通过主被动结合的方式，实时不间断地采集用户网络中各种不同厂商的安全设备、网络设备、主机、操作系统、以及各种应用系统产生的海量日志信息，并将这些信息汇集到审计中心，进行集中化存储（可根据日志规模大小进行分布式存储，支持水平弹性扩展和数据高可靠性存储）、索引、备份、全文检索、实时搜索、审计、告警、响应，并出具丰富的报表报告，获悉全网的整体安全运行态势，实现全生命周期的日志管理。",
        "monthly_price": 7359,
        "yearly_price": 88308,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年75折，3、4、5年65折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 26,
        "category": "日志审计",
        "name": "日志审计-500资产",
        "spec": "支持500个日志源（每个日志源对应为一个IP）；通过主被动结合的方式，实时不间断地采集用户网络中各种不同厂商的安全设备、网络设备、主机、操作系统、以及各种应用系统产生的海量日志信息，并将这些信息汇集到审计中心，进行集中化存储（可根据日志规模大小进行分布式存储，支持水平弹性扩展和数据高可靠性存储）、索引、备份、全文检索、实时搜索、审计、告警、响应，并出具丰富的报表报告，获悉全网的整体安全运行态势，实现全生命周期的日志管理。",
        "monthly_price": 15639,
        "yearly_price": 187668,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年75折，3、4、5年65折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 27,
        "category": "日志审计",
        "name": "日志审计-存储扩容",
        "spec": "支持对数据盘进行扩容500/TB",
        "monthly_price": 500,
        "yearly_price": 6000,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年75折，3、4、5年65折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 35,
        "category": "堡垒机",
        "name": "堡垒机-10资产",
        "spec": "支持10资产管理；4A统一安全管控平台，为企业提供集单点登录、统一资产管理、多终端访问协议、文件传输、会话协同等功能于一体的运维管理服务。",
        "monthly_price": 1020,
        "yearly_price": 12240,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年7折，3、4、5年5折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 36,
        "category": "堡垒机",
        "name": "堡垒机-20资产",
        "spec": "支持20资产管理；4A统一安全管控平台，为企业提供集单点登录、统一资产管理、多终端访问协议、文件传输、会话协同等功能于一体的运维管理服务。",
        "monthly_price": 1280,
        "yearly_price": 15360,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年7折，3、4、5年5折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 37,
        "category": "堡垒机",
        "name": "堡垒机-50资产",
        "spec": "支持50资产管理；4A统一安全管控平台，为企业提供集单点登录、统一资产管理、多终端访问协议、文件传输、会话协同等功能于一体的运维管理服务。",
        "monthly_price": 2600,
        "yearly_price": 31200,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年7折，3、4、5年5折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 38,
        "category": "堡垒机",
        "name": "堡垒机-100资产",
        "spec": "支持100资产管理；4A统一安全管控平台，为企业提供集单点登录、统一资产管理、多终端访问协议、文件传输、会话协同等功能于一体的运维管理服务。",
        "monthly_price": 4600,
        "yearly_price": 55200,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年7折，3、4、5年5折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 39,
        "category": "堡垒机",
        "name": "堡垒机-200资产",
        "spec": "支持200资产管理；4A统一安全管控平台，为企业提供集单点登录、统一资产管理、多终端访问协议、文件传输、会话协同等功能于一体的运维管理服务。",
        "monthly_price": 6200,
        "yearly_price": 74400,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年7折，3、4、5年5折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 40,
        "category": "堡垒机",
        "name": "堡垒机-500资产",
        "spec": "支持500资产管理；4A统一安全管控平台，为企业提供集单点登录、统一资产管理、多终端访问协议、文件传输、会话协同等功能于一体的运维管理服务。",
        "monthly_price": 9200,
        "yearly_price": 110400,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年7折，3、4、5年5折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 41,
        "category": "堡垒机",
        "name": "堡垒机-1000资产",
        "spec": "支持1000资产管理；4A统一安全管控平台，为企业提供集单点登录、统一资产管理、多终端访问协议、文件传输、会话协同等功能于一体的运维管理服务。",
        "monthly_price": 14170,
        "yearly_price": 170040,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年7折，3、4、5年5折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 42,
        "category": "堡垒机",
        "name": "堡垒机-存储扩容",
        "spec": "支持对数据盘进行扩容",
        "monthly_price": 500,
        "yearly_price": 6000,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，1年85折，2年7折，3、4、5年5折。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 50,
        "category": "数据库审计",
        "name": "数据库审计-4资产",
        "spec": "支持4数据库实例；通过Agent抓包方式旁路部署，提供数据库审计、SQL注入攻击检测、风险操作识别等功能，保障云上数据库的安全。",
        "monthly_price": 3333,
        "yearly_price": 39996,
        "yearly_discount": 0.833,
        "discount_rate": 0.833,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，享受1年及以上8.33折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 51,
        "category": "数据库审计",
        "name": "数据库审计-8资产",
        "spec": "支持8数据库实例；通过Agent抓包方式旁路部署，提供数据库审计、SQL注入攻击检测、风险操作识别等功能，保障云上数据库的安全。",
        "monthly_price": 6250,
        "yearly_price": 75000,
        "yearly_discount": 0.833,
        "discount_rate": 0.833,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，享受1年及以上8.33折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 52,
        "category": "数据库审计",
        "name": "数据库审计-16资产",
        "spec": "支持16数据库实例；通过Agent抓包方式旁路部署，提供数据库审计、SQL注入攻击检测、风险操作识别等功能，保障云上数据库的安全。",
        "monthly_price": 11667,
        "yearly_price": 140004,
        "yearly_discount": 0.833,
        "discount_rate": 0.833,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，享受1年及以上8.33折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 53,
        "category": "数据库审计",
        "name": "数据库审计-32资产",
        "spec": "支持32数据库实例；通过Agent抓包方式旁路部署，提供数据库审计、SQL注入攻击检测、风险操作识别等功能，保障云上数据库的安全。",
        "monthly_price": 22400,
        "yearly_price": 268800,
        "yearly_discount": 0.833,
        "discount_rate": 0.833,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，享受1年及以上8.33折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 54,
        "category": "数据库审计",
        "name": "数据库审计-存储扩容",
        "spec": "支持对数据盘进行扩容500/TB",
        "monthly_price": 500,
        "yearly_price": 6000,
        "yearly_discount": 0.833,
        "discount_rate": 0.833,
        "discount_desc": "包年订购折扣：针对一次性包年付费服务，享受1年及以上8.33折优惠。",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 59,
        "category": "漏洞扫描",
        "name": "漏洞扫描-10资产",
        "spec": "支持10个IP地址；能够对Web应用的资产进行识别分类以及对Web应用进行深度弱点探测。通过漏洞产生的原理和渗透测试的方法，快速分析出被测目标所开放的端口服务和对应的协议信息，发现资产暴露面。漏洞库覆盖国内外常见CMS、中间件、操作系统等严重漏洞，帮助用户全面分析Web应用网络环境中存在的安全弱点。",
        "monthly_price": 937,
        "yearly_price": 11244,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 60,
        "category": "漏洞扫描",
        "name": "漏洞扫描-20资产",
        "spec": "支持20个IP地址；能够对Web应用的资产进行识别分类以及对Web应用进行深度弱点探测。通过漏洞产生的原理和渗透测试的方法，快速分析出被测目标所开放的端口服务和对应的协议信息，发现资产暴露面。漏洞库覆盖国内外常见CMS、中间件、操作系统等严重漏洞，帮助用户全面分析Web应用网络环境中存在的安全弱点。",
        "monthly_price": 1339,
        "yearly_price": 16068,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 61,
        "category": "漏洞扫描",
        "name": "漏洞扫描-50资产",
        "spec": "支持50个IP地址；能够对Web应用的资产进行识别分类以及对Web应用进行深度弱点探测。通过漏洞产生的原理和渗透测试的方法，快速分析出被测目标所开放的端口服务和对应的协议信息，发现资产暴露面。漏洞库覆盖国内外常见CMS、中间件、操作系统等严重漏洞，帮助用户全面分析Web应用网络环境中存在的安全弱点。",
        "monthly_price": 3493,
        "yearly_price": 41916,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 62,
        "category": "漏洞扫描",
        "name": "漏洞扫描-100资产",
        "spec": "支持100个IP地址；能够对Web应用的资产进行识别分类以及对Web应用进行深度弱点探测。通过漏洞产生的原理和渗透测试的方法，快速分析出被测目标所开放的端口服务和对应的协议信息，发现资产暴露面。漏洞库覆盖国内外常见CMS、中间件、操作系统等严重漏洞，帮助用户全面分析Web应用网络环境中存在的安全弱点。",
        "monthly_price": 4990,
        "yearly_price": 59880,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 63,
        "category": "漏洞扫描",
        "name": "漏洞扫描-200资产",
        "spec": "支持200个IP地址；能够对Web应用的资产进行识别分类以及对Web应用进行深度弱点探测。通过漏洞产生的原理和渗透测试的方法，快速分析出被测目标所开放的端口服务和对应的协议信息，发现资产暴露面。漏洞库覆盖国内外常见CMS、中间件、操作系统等严重漏洞，帮助用户全面分析Web应用网络环境中存在的安全弱点。",
        "monthly_price": 10530,
        "yearly_price": 126360,
        "yearly_discount": 1.0,
        "discount_rate": 1.0,
        "discount_desc": "",
        "remark": "",
        "require_host": False,
        "host_id": None,
    },
]

# 云主机列表
HOSTS: List[Dict] = [
{
        "id": 13,
        "category": "Web应用防火墙-单机版-云主机",
        "name": "Web应用防火墙-独享版-云主机",
        "spec": "c6.xlarge.2 | 4vCpu 8GB内存 | 系统盘 普通IO 40GB | 数据盘 普通IO 100GB | 1台",
        "monthly_price": 462,
        "yearly_price": 5544,
        "yearly_discount": 0.8500000000000001,
        "discount_rate": 0.8500000000000001,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 17,
        "category": "下一代防火墙-云主机",
        "name": "下一代防火墙-标准版-云主机",
        "spec": "c6.large.2 | 2vCpu 4GB内存 | 系统盘 普通IO 40GB | 1台",
        "monthly_price": 222,
        "yearly_price": 2664,
        "yearly_discount": 0.8500000000000001,
        "discount_rate": 0.8500000000000001,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 18,
        "category": "下一代防火墙-云主机",
        "name": "下一代防火墙-高级版-云主机",
        "spec": "c6.large.2 | 2vCpu 4GB内存 | 系统盘 普通IO 40GB | 1台",
        "monthly_price": 222,
        "yearly_price": 2664,
        "yearly_discount": 0.8500000000000001,
        "discount_rate": 0.8500000000000001,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 19,
        "category": "下一代防火墙-云主机",
        "name": "下一代防火墙-企业版-云主机",
        "spec": "c6.xlarge.2 | 4vCpu 8GB内存 | 系统盘 普通IO 40GB | 1台",
        "monthly_price": 432,
        "yearly_price": 5184,
        "yearly_discount": 0.8500000000000001,
        "discount_rate": 0.8500000000000001,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 28,
        "category": "日志审计云主机",
        "name": "日志审计-10资产-云主机",
        "spec": "c6.2xlarge.4 | 8vCpu 32GB内存 | 系统盘 普通IO 40GB | 数据盘 普通IO 512GB | 1台",
        "monthly_price": 1166,
        "yearly_price": 13987,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 29,
        "category": "日志审计云主机",
        "name": "日志审计-15资产-云主机",
        "spec": "c6.2xlarge.4 | 8vCpu 32GB内存 | 系统盘 普通IO 40GB | 数据盘 普通IO 1024GB | 1台",
        "monthly_price": 1319,
        "yearly_price": 15830,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 30,
        "category": "日志审计云主机",
        "name": "日志审计-20资产-云主机",
        "spec": "c6.2xlarge.4 | 8vCpu 32GB内存 | 系统盘 普通IO 40GB | 数据盘 普通IO 1024GB | 1台",
        "monthly_price": 1319,
        "yearly_price": 15830,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 31,
        "category": "日志审计云主机",
        "name": "日志审计-50资产-云主机",
        "spec": "c6.2xlarge.4 | 8vCpu 32GB内存 | 系统盘 普通IO 40GB | 数据盘 普通IO 2048GB | 1台",
        "monthly_price": 1626,
        "yearly_price": 19517,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 32,
        "category": "日志审计云主机",
        "name": "日志审计-100资产-云主机",
        "spec": "c6.4xlarge.2 | 16vCpu 32GB内存 | 系统盘 普通IO 40GB | 数据盘 普通IO 4096GB | 1台",
        "monthly_price": 2921,
        "yearly_price": 35050,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 33,
        "category": "日志审计云主机",
        "name": "日志审计-200资产-云主机",
        "spec": "c6.4xlarge.4 | 16vCpu 64GB内存 | 系统盘 普通IO 40GB | 数据盘 普通IO 6144GB | 1台",
        "monthly_price": 3855,
        "yearly_price": 46262,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 34,
        "category": "日志审计云主机",
        "name": "日志审计-500资产-云主机",
        "spec": "c6.4xlarge.4 | 16vCpu 64GB内存 | 系统盘 普通IO 40GB | 数据盘 普通IO 10240GB | 1台台",
        "monthly_price": 5084,
        "yearly_price": 61008,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 43,
        "category": "堡垒机-云主机",
        "name": "堡垒机-10资产-云主机",
        "spec": "c6.large.2 | 2vCpu 4GB内存 | 系统盘 普通IO 40GB | 数据盘 普通IO 300GB | 1台",
        "monthly_price": 312,
        "yearly_price": 3744,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 44,
        "category": "堡垒机-云主机",
        "name": "堡垒机-20资产-云主机",
        "spec": "c6.large.4 | 2vCpu 8GB内存 | 系统盘 普通IO 50GB | 数据盘 普通IO 300GB | 1台",
        "monthly_price": 355,
        "yearly_price": 4260,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 45,
        "category": "堡垒机-云主机",
        "name": "堡垒机-50资产-云主机",
        "spec": "c6.xlarge.4 | 4vCpu 16GB内存 | 系统盘 普通IO 50GB | 数据盘 普通IO 500GB | 1台",
        "monthly_price": 665,
        "yearly_price": 7980,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 46,
        "category": "堡垒机-云主机",
        "name": "堡垒机-100资产-云主机",
        "spec": "c6.2xlarge.4 | 8vCpu 32GB内存 | 系统盘 普通IO 50GB | 数据盘 普通IO 800GB | 1台",
        "monthly_price": 1255,
        "yearly_price": 15060,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 47,
        "category": "堡垒机-云主机",
        "name": "堡垒机-200资产-云主机",
        "spec": "c6.2xlarge.4 | 8vCpu 32GB内存 | 系统盘 普通IO 50GB | 数据盘 普通IO 800GB | 1台",
        "monthly_price": 1255,
        "yearly_price": 15060,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 48,
        "category": "堡垒机-云主机",
        "name": "堡垒机-500资产-云主机",
        "spec": "m6.3xlarge.8 | 12vCpu 96GB内存 | 系统盘 普通IO 50GB | 数据盘 普通IO 2048GB | 1台",
        "monthly_price": 2609,
        "yearly_price": 31313,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 49,
        "category": "堡垒机-云主机",
        "name": "堡垒机-1000资产-云主机",
        "spec": "c6.4xlarge.4 | 16vCpu 64GB内存 | 系统盘 普通IO 50GB | 数据盘 普通IO 2048GB | 1台",
        "monthly_price": 2629,
        "yearly_price": 31553,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 55,
        "category": "数据库审计-云主机",
        "name": "数据库审计-32资产-云主机",
        "spec": "c6.4xlarge.4 | 16vCpu 64GB内存 | 系统盘 普通IO 100GB | 数据盘 普通IO 5120GB | 1台",
        "monthly_price": 3566,
        "yearly_price": 42792,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 56,
        "category": "数据库审计-云主机",
        "name": "数据库审计-16资产-云主机",
        "spec": "c6.4xlarge.4 | 16vCpu 64GB内存 | 系统盘 普通IO 100GB | 数据盘 普通IO 2048GB | 1台",
        "monthly_price": 2644,
        "yearly_price": 31733,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 57,
        "category": "数据库审计-云主机",
        "name": "数据库审计-8资产-云主机",
        "spec": "c6.2xlarge.4 | 8vCpu 32GB内存 | 系统盘 普通IO 100GB | 数据盘 普通IO 1024GB | 1台台",
        "monthly_price": 6250,
        "yearly_price": 75000,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 58,
        "category": "数据库审计-云主机",
        "name": "数据库审计-4资产-云主机",
        "spec": "c6.xlarge.4 | 4vCpu 16GB内存 | 系统盘 普通IO 100GB | 数据盘 普通IO 512GB | 1台",
        "monthly_price": 684,
        "yearly_price": 8203,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 64,
        "category": "漏洞扫描-云主机",
        "name": "漏洞扫描-10资产-云主机",
        "spec": "c6.xlarge.2 | 4vCpu 8GB内存 | 系统盘 普通IO 200GB | 数据盘 普通IO 1024GB | 1台",
        "monthly_price": 787,
        "yearly_price": 9446,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 65,
        "category": "漏洞扫描-云主机",
        "name": "漏洞扫描-20资产-云主机",
        "spec": "c6.xlarge.2 | 4vCpu 8GB内存 | 系统盘 普通IO 200GB | 数据盘 普通IO 1024GB | 1台",
        "monthly_price": 787,
        "yearly_price": 9446,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 66,
        "category": "漏洞扫描-云主机",
        "name": "漏洞扫描-50资产-云主机",
        "spec": "c6.4xlarge.2 | 16vCpu 32GB内存 | 系统盘 普通IO 200GB | 数据盘 普通IO 1024GB | 1台",
        "monthly_price": 2047,
        "yearly_price": 24566,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 67,
        "category": "漏洞扫描-云主机",
        "name": "漏洞扫描-100资产-云主机",
        "spec": "c6.3xlarge.2 | 12vCpu 24GB内存 | 系统盘 普通IO 200GB | 数据盘 普通IO 1024GB | 1台",
        "monthly_price": 1627,
        "yearly_price": 19526,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 68,
        "category": "漏洞扫描-云主机",
        "name": "漏洞扫描-200资产-云主机",
        "spec": "c6.3xlarge.2 | 12vCpu 24GB内存 | 系统盘 普通IO 200GB | 数据盘 普通IO 1024GB | 1台",
        "monthly_price": 1627,
        "yearly_price": 19526,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
{
        "id": 69,
        "category": "管理节点-云主机",
        "name": "管理节点-云主机",
        "spec": "c6.xlarge.2 | 4vCpu 8GB内存 | 系统盘 普通IO 40GB | 1台",
        "monthly_price": 432,
        "yearly_price": 5184,
        "yearly_discount": 0.85,
        "discount_rate": 0.85,
        "discount_desc": "1年8.5折、2年7折、3年5",
        "remark": "合营池云主机费用",
        "require_host": False,
        "host_id": None,
    },
]

# 三级等保基础版产品 ID 列表
BASIC_EDITION_IDS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 20, 21, 22, 23, 24, 25, 26, 27,
                 35, 36, 37, 38, 39, 40, 41, 42,
                 50, 51, 52, 53, 54,
                 59, 60, 61, 62, 63]


def get_all_products() -> List[Dict]:
    return copy.deepcopy(PRODUCTS)

def get_all_hosts() -> List[Dict]:
    return copy.deepcopy(HOSTS)

def get_product_by_id(pid: int) -> Dict:
    for p in PRODUCTS:
        if p.get("id") == pid:
            return copy.deepcopy(p)
    return None

def get_basic_edition_products() -> List[Dict]:
    return [copy.deepcopy(p) for p in PRODUCTS if p.get("id") in BASIC_EDITION_IDS]

def get_host_by_id(host_id: int) -> Dict:
    """根据主机ID获取主机信息"""
    for host in HOSTS:
        if host.get("id") == host_id:
            return copy.deepcopy(host)
    return None

def calculate_price(product: Dict, quantity: int = 1) -> Dict:
    qty = max(1, quantity)
    monthly = product.get("monthly_price", 0) * qty
    yearly = product.get("yearly_price", 0) * qty
    discounted = yearly * product.get("yearly_discount", 1)
    price_45 = discounted * 0.45
    price_55 = discounted * 0.55
    return {
        "monthly": monthly,
        "yearly": yearly,
        "discounted": discounted,
        "price_45": price_45,
        "price_55": price_55,
    }

def generate_quote_data(selected_products, quantities, include_host, include_mgmt_host):
    data = []
    for prod in selected_products:
        pid = prod.get("id")
        qty = quantities.get(pid, 1)
        price_info = calculate_price(prod, qty)
        row = {
            "seq": pid, "product": prod.get("name"), "spec": prod.get("spec"),
            "qty": qty, "monthly": price_info["monthly"], "yearly": price_info["yearly"],
            "discounted": price_info["discounted"], "price_45": price_info["price_45"],
            "price_55": price_info["price_55"], "discount_desc": prod.get("discount_desc", ""),
            "remark": prod.get("remark", ""), "is_host": False,
        }
        data.append(row)
    if include_host:
        for host in HOSTS:
            pid = host.get("id")
            qty = quantities.get(pid, 1)
            price_info = calculate_price(host, qty)
            row = {
                "seq": pid, "product": host.get("name"), "spec": host.get("spec"),
                "qty": qty, "monthly": price_info["monthly"], "yearly": price_info["yearly"],
                "discounted": price_info["discounted"], "price_45": price_info["price_45"],
                "price_55": price_info["price_55"], "discount_desc": host.get("discount_desc", ""),
                "remark": host.get("remark", ""), "is_host": True,
            }
            data.append(row)
    return data

def get_totals(data):
    totals = {"monthly": 0.0, "yearly": 0.0, "discounted": 0.0, "price_45": 0.0, "price_55": 0.0}
    for row in data:
        totals["monthly"] += float(row.get("monthly", 0))
        totals["yearly"] += float(row.get("yearly", 0))
        totals["discounted"] += float(row.get("discounted", 0))
        totals["price_45"] += float(row.get("price_45", 0))
        totals["price_55"] += float(row.get("price_55", 0))
    return totals